#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "\n\t >>> Running PHP Lint..."
for FILE in $SFILES
do
    php -l -d display_errors=0 $PROJECT/$FILE
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]; then
    error=false
    echo "\n\t >>> Running Code Sniffer. Code standard PSR2."
    ./vendor/bin/phpcs --standard=PSR12 --encoding=utf-8 -n -p $FILES
    if [ "$?" -gt 0 ]
    then
        error=true
    fi
    if [ "$error" != false ]; then 
        echo "Fix the error before commit!"
        echo "Para correção automática, execute: \n"
        echo "  ./vendor/bin/phpcbf $FILES"
        exit 1
    fi
fi

if [ "$FILES" != "" ]
then
    error=false
    echo "\n\t >>> Running php-assumptions"
    for i in $FILES; do 
        ./vendor/bin/phpa $i
        if [ "$?" -gt 0 ]
        then
            error=true
        else
            echo "OK: $i\n"
        fi
    done
    if [ "$error" != false ]
    then
        echo "\nCorrija os erros antes do Commit!"
        exit 1
    fi
fi

exit $?
